
package com.example.oldCompanySystem.Entity.BOMEntity;

import com.example.oldCompanySystem.bl.BOMPort;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BOMService", targetNamespace = "http://www.oldSystem.com/wsdl", wsdlLocation = "file:/C:/Users/82582/Desktop/\u5b9e\u8df5\u8bfe/oldSystem/xml/wsdl/BOM.wsdl")
public class BOMService
    extends Service
{

    private final static URL BOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOMSERVICE_EXCEPTION;
    private final static QName BOMSERVICE_QNAME = new QName("http://www.oldSystem.com/wsdl", "BOMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/82582/Desktop/\u5b9e\u8df5\u8bfe/oldSystem/xml/wsdl/BOM.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOMSERVICE_WSDL_LOCATION = url;
        BOMSERVICE_EXCEPTION = e;
    }

    public BOMService() {
        super(__getWsdlLocation(), BOMSERVICE_QNAME);
    }

    public BOMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOMSERVICE_QNAME, features);
    }

    public BOMService(URL wsdlLocation) {
        super(wsdlLocation, BOMSERVICE_QNAME);
    }

    public BOMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOMSERVICE_QNAME, features);
    }

    public BOMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BOMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BOMPort
     */
    @WebEndpoint(name = "BOMPort")
    public BOMPort getBOMPort() {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "BOMPort"), BOMPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BOMPort
     */
    @WebEndpoint(name = "BOMPort")
    public BOMPort getBOMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "BOMPort"), BOMPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOMSERVICE_EXCEPTION!= null) {
            throw BOMSERVICE_EXCEPTION;
        }
        return BOMSERVICE_WSDL_LOCATION;
    }

}
